# Generated by Django 3.0.3 on 2020-07-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.TextField(choices=[('EF', 'ethnic'), ('FF', 'fast_food'), ('FC', 'fast_casual'), ('CD', 'casual_dining'), ('PC', 'premium_casual'), ('FS', 'family_style'), ('FD', 'fine_dining'), ('PB', 'pub')], max_length=2)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=20)),
                ('website', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('opening_hours', models.CharField(max_length=50)),
                ('price_level', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
