# Generated by Django 3.0.3 on 2020-07-06 09:54

import apps.registrations.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20200706_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 9, 54, 22, 811350, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='registration',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default=apps.registrations.models.code_generator, max_length=10),
        ),
    ]
