# Generated by Django 3.0.3 on 2020-07-07 18:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20200707_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 18, 33, 58, 980466, tzinfo=utc)),
        ),
    ]
