# Generated by Django 3.0.3 on 2020-07-08 19:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_auto_20200708_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 19, 37, 4, 459681, tzinfo=utc)),
        ),
    ]
