# Generated by Django 3.0.3 on 2020-07-09 07:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_auto_20200708_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 7, 50, 6, 432808, tzinfo=utc)),
        ),
    ]
