# Generated by Django 3.0.3 on 2020-07-09 10:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_auto_20200709_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 10, 10, 20, 35561, tzinfo=utc)),
        ),
    ]
