
// Login types

export const USER_LOGIN = 'USER_LOGIN'
export const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER'

// Logout types

export const USER_LOGOUT = 'USER_LOGOUT'


// Error Types

export const SET_ERROR = 'SET_ERROR'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

// Search Types

export const GET_ALL_USERS = 'GET_ALL_USERS'
export const CHANGE_SEARCH_TAB_INDEX = 'CHANGE_SEARCH_TAB_INDEX'


// Review Types

export const GET_MY_LIKED_REVIEWS = 'GET_MY_LIKED_REVIEWS'
export const GET_MY_COMMENTED_REVIEWS = 'GET_MY_COMMENTED_REVIEWS'
export const UPDATE_REVIEW_IN_LIST = 'UPDATE_REVIEW_IN_LIST'
export const ADD_REVIEW_TO_LIST = 'ADD_REVIEW_TO_LIST'
export const REMOVE_REVIEW_IN_LIST = 'REMOVE_REVIEW_IN_LIST'
export const LIKE_REVIEW_IN_SEARCH = 'LIKE_REVIEW_IN_SEARCH'
export const LIKE_REVIEW_IN_RESTAURANT_PROFILE = 'LIKE_REVIEW_IN_RESTAURANT_PROFILE'

