
// Login types

export const USER_LOGIN = 'USER_LOGIN'
export const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER'

// Logout types

export const USER_LOGOUT = 'USER_LOGOUT'


// Error Types

export const SET_ERROR = 'SET_ERROR'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

// Search Types

export const SET_USER_PROFILES = 'SET_USER_PROFILES'
export const SET_RESTAURANTS = 'SET_RESTAURANTS'
export const SET_REVIEWS = 'SET_REVIEWS'
export const CHANGE_SEARCH_TAB_INDEX = 'CHANGE_SEARCH_TAB_INDEX'
export const RESET_SEARCH = 'RESET_SEARCH'


// Review Types

export const GET_MY_LIKED_REVIEWS = 'GET_MY_LIKED_REVIEWS'
export const GET_MY_COMMENTED_REVIEWS = 'GET_MY_COMMENTED_REVIEWS'
export const UPDATE_REVIEW_IN_LIST = 'UPDATE_REVIEW_IN_LIST'
export const REMOVE_REVIEW_IN_LIST = 'REMOVE_REVIEW_IN_LIST'



// Restaurant Types

export const SET_RESTAURANT_REVIEWS = 'SET_RESTAURANT_REVIEWS'
export const ADD_REVIEW_TO_LIST = 'ADD_REVIEW_TO_LIST'
export const SET_RESTAURANT_OBJ = 'SET_RESTAURANT_OBJ'


// User Profile Types

export const SET_USER_PROFILE_REVIEWS = 'SET_USER_PROFILE_REVIEWS'
export const SET_USER_PROFILE_RESTAURANTS = 'SET_USER_PROFILE_RESTAURANTS'
export const SET_USER_PROFILE_COMMENTS = 'SET_USER_PROFILE_COMMENTS'
export const SET_USER_PROFILE_USER = 'SET_USER_PROFILE_USER'


// Like types

export const LIKE_RESTAURANT_PROFILE_REVIEW = 'LIKE_RESTAURANT_PROFILE_REVIEW'
export const UPDATE_LIKED_REVIEW_IN_SEARCH_LIST = 'UPDATE_REVIEW_IN_SEARCH_LIST'
